### ISSUE TITLE
bug: String.prototype.replaceAll does not exist in Node.js v14

### ISSUE THREAD

**Issue by boneskull** [favware/esbuild-plugin-version-injector#16]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

 `String.prototype.replaceAll` is used on L87 of `dist/index.js`, and that function does not exist in Node.js v14.  Node.js v14 is not run in CI, so I'm not surprised this wasn't caught.

### Steps To Reproduce

Here's an example of a build failing in Node.js v14:

https://github.com/boneskull/unexpected-eventemitter/actions/runs/3517048877/jobs/5894364630

### Expected behavior

well... not fail with a `TypeError`, I guess

**Comment by boneskull** [comment]
I'd send a PR to fix this, or you might just want to drop Node.js v14 support, IDK.

**Comment by favna** [comment]
Make a PR adding a polyfill for now I suppose. Node 14 isn't _yet_ EOL (scheduled for 2023-04-30) so I think it's good to support it. 

I think `string.prototype.replaceall` on npm will do

**Comment by favna** [comment]
Fixed in 1.0.1 by adding a polyfill

**Comment by favna** [comment]
Released v1.0.2 which fixed a regression bug due to regex not being escaped.
